// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieeubgunjhepkpqlyupf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllZXViZ3VuamhlcGtwcWx5dXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NTI3NDYsImV4cCI6MjA1NjQyODc0Nn0.Z9qgKm2AHUj4mthRKTzrAWE3Q8XtoYGG52rBC3CzkXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);